-- AlterTable
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "examples" JSONB;
ALTER TABLE "Problem" ADD COLUMN IF NOT EXISTS "constraints" JSONB;

-- AlterTable
ALTER TABLE "TestCaseSet" ADD COLUMN IF NOT EXISTS "starterCode" JSONB;
ALTER TABLE "TestCaseSet" ADD COLUMN IF NOT EXISTS "functionNameMap" JSONB;
